export enum FmsHEvent {
  UPPER_INC = 'UpperKnobInc',
  UPPER_DEC = 'UpperKnobDec',
  LOWER_INC = 'LowerKnobInc',
  LOWER_DEC = 'LowerKnobDec',
  MENU = 'Menu',
  ENT = 'Enter',
  CLR = 'Clr',
  DIRECTTO = 'DirectTo',
  UPPER_PUSH = 'UpperKnobPush',
  FPL = 'FPL',
  PROC = 'Proc',
  RANGE_INC = 'RangeInc',
  RANGE_DEC = 'RangeDec',
  JOYSTICK_PUSH = 'JoystickPush',
  JOYSTICK_LEFT = 'JoystickLeft',
  JOYSTICK_UP = 'JoystickUp',
  JOYSTICK_RIGHT = 'JoystickRight',
  JOYSTICK_DOWN = 'JoystickDown',
  CLR_LONG = 'ClrLong'
}