on:
  issues:
    types: [opened]
name: Issue opened
jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: V1.0.0 Roadmap
          COLUMN: Investigating
      - uses: technote-space/auto-card-labeler@gh-actions
