on:
  issues:
    types: [opened]
name: Issue opened
jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: V1.0.0 Roadmap
          COLUMN: Investigating
  triage:
    name: Auto card labeler
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/auto-card-labeler@gh-actions
